### ISSUE TITLE
Way to set number formatting defaults 

### ISSUE THREAD

**Issue by WvanLelyveld** [randoum/autonumeric-rails#10]
I think right now the way to set defaults is as mentioned on [the autoNumeric page](https://github.com/BobKnothe/autoNumeric):

```
    $(document).ready(function () {          
        $.extend($.fn.autoNumeric.defaults, {              
            aSep: '@System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberGroupSeparator',              
            aDec: '@System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.NumberDecimalSeparator',
            aSign: '@System.Threading.Thread.CurrentThread.CurrentCulture.NumberFormat.CurrencySymbol'
        });      

        $('selector').autoNumeric('init'); 

    });
```

Is there a way to set these defaults easier through this gem?
If not, that would be my feature request.

Of course setting global defaults is easy enough, I want an easy way to do this in dynamically in Rails, like updating it in the controller some way.

**Comment by randoum** [comment]
The gem actually does not handle default configuration. Pull requests are welcome :)

**Comment by randoum** [comment]
@WvanLelyveld Feel free to work on the PR and submit it to me, I close this thread for the meantime
