### ISSUE TITLE
Sprockets::FileNotFound: couldn't find file 'autonumeric'

### ISSUE THREAD

**Issue by dwilkie** [randoum/autonumeric-rails#12]
The following error occurs when assets are precompiled

```
Sprockets::FileNotFound: couldn't find file 'autonumeric'
```

**Comment by dwilkie** [comment]
Fixed by https://github.com/randoum/autonumeric-rails/commit/209af266a055465a991aeb228a154f566ed230f3

**Comment by lehresman** [comment]
Can we get a new release with this fix?
