### ISSUE TITLE
autoNumeric('destroy') not working

### ISSUE THREAD

**Issue by NilAndNull** [randoum/autonumeric-rails#5]
In the following example, I'm trying to do a fallback when a touch device is detected and the browser supports the input type number. 

The problem is that, even after the autoNumeric('destroy') is called, the browser console still gives this error, after the user inputs some number and focus outside the input form:
Error: You must initialize autoNumeric('init', {options}) prior to calling the 'get' method

```
$(document).ready(function(){

  // Changes input type to number and disables autonumeric, to use the native
  // data input number type.
  if (Modernizr.touch && Modernizr.inputtypes.number) {
    $('.number-input-field').removeAttr('data-autonumeric');
    $('.number-input-field').autoNumeric('destroy');
    $('.number-input-field').attr('type', 'number');
    $(document).trigger('refresh_autonumeric');
  }
});
```

**Comment by randoum** [comment]
Just after removing the `data-autonumeric` attribute with:
```
$('.number-input-field').removeAttr('data-autonumeric');
```

Try removing the data (which is cached by jQuery) with:
```
$('.number-input-field').removeData('autonumeric');
```

Please let me know if this works

**Comment by NilAndNull** [comment]
:O 
It worked perfectly. No JS exception is thrown anymore. 

So the trick, is removing also the Data, so it removes the jQuery cache... :/ 

I read the autonumeric documentation several times, but I didn't find any reference to that, only the destroy parameter...

The $('.number-input-field').autoNumeric('destroy'); should be enough to disable autoNumeric (including cached data). 

Do you think this make sense or not at all? 

If it makes sense I can open an issue in autonumeric library github.

Thank you!

**Comment by randoum** [comment]
`.autoNumeric('destroy')` is part of `autoNumeric`, unlike the `data-autonumeric` attribute which is an addition of `autonumeric-rails`, so it won't make sense to open an issue there.

Though if you wish to contribute you can provide a pull request to perform a destroy and remove the data attribute in one single call.

Glad to know you fixed the problem, I'll close this issue

**Comment by NilAndNull** [comment]
Today, I run again the code and it returned an exception! (I might have not tested correctly yesterday).

My code:

```
$(document).ready(function(){
  // Changes input type to number and disables autonumeric, to use the native
  // data input number type.
  //if (Modernizr.touch && Modernizr.inputtypes.number) {
  if (true) {
    
    // Remove all autonumeric data parameters and hidden field
    $('.number-input-field').removeAttr('data-autonumeric');
    $('.number-input-field').removeData('autonumeric');
    $('#' + $('.number-input-field').attr('id') + '_val').remove();

    $('.number-input-field').autoNumeric('destroy');

    $('.number-input-field').attr('type', 'number');
    $(document).trigger('refresh_autonumeric');
  }
});
```

I click on the input field, write a number and click outside the input field a it throws the following exception:

![captura de ecra 2015-03-4 as 11 58 44](https://cloud.githubusercontent.com/assets/10235058/6483189/0a548968-c266-11e4-8d96-e629781f40a7.jpg)

I don't understand. I'm cleaning everything (data and hidden field), then I call destroy, then i call refresh. 

And it seems that some "callbacks" are still called after that. :/

**Comment by NilAndNull** [comment]
Ok.

I've solved using the jQuery off.

I read you autonumeric_ujs.js code and I saw that you use 'on' jQuery. I used the opposite method 'off' and it worked.

The final code now working is:

```
$(document).ready(function(){

  // Changes input type to number and disables autonumeric, to use the native
  // data input number type.
  if (Modernizr.touch && Modernizr.inputtypes.number) {

    // Remove all autonumeric data parameters, events and hidden field
    $('input[data-autonumeric]').each(function() {
      $(this).removeAttr('data-autonumeric');
      $(this).removeData('autonumeric');
      $('#' + $(this).attr('id') + '_val').remove();
      $(this).off('keyup blur');

      $(this).autoNumeric('destroy');

      $(this).attr('type', 'number');
    });

    $(document).trigger('refresh_autonumeric');   
  }
});
```

I'm not very good with JS or jQuery (never learned them), so I don't know if I'm breaking somethig with this solution. 

I might be a good change to add a remove/destroy/disable method in autonumeric_ujs.js to perform the teardown code, to properly remove autonumeric. 

Something like:

```

AutonumericRails.prototype.remove_hidden_field = function() {
        this.removeAfter(this.field);
    };

AutonumericRails.prototype.destroy_autonumeric = function() {
        this.field.removeAttr('data-autonumeric');
        this.field.removeData('autonumeric');
        this.remove_hidden_field();
        this.field.off('keyup blur');
        this.field.autoNumeric('destroy', $.parseJSON(this.field.attr('data-autonumeric')));
    };
```

**Comment by randoum** [comment]
Thanks for the insights. I've taken your code and included it in autonumeric-rails. Would you mind to test it?

It is not published in gem for now so you need to fetch it from github. In your gem file: `gem 'autonumeric-rails', github: 'randoum/autonumeric-rails'`

So your code will become
``` javascript
 if (Modernizr.touch && Modernizr.inputtypes.number) {
    $('input[data-autonumeric]').each(function() {
      var element = $(this)
      AutonumericRails.delete_autonumeric_object(element);
      element.attr('type', 'number');
    });

    $(document).trigger('refresh_autonumeric');   
  }
```

**Note**: This will not un-sanitize the field's value, and you must do it manually.

**Comment by NilAndNull** [comment]
Worked like a charm :)

I've only had to change to:

```
AutonumericRails.delete_autonumeric_object($(this));
$(this).attr('type', 'number');
```

The change of attribute type to number didn't work with element. 

The delete_autonumeric_object worked perfectly. The HTML was clean and not a single JS exception.

Cheers.

**Comment by randoum** [comment]
Perfect, I'll include it in the next gem release then
Cheers
