### ISSUE TITLE
"ERROR: directory is already being watched!"

### ISSUE THREAD

**Issue by groe** [randoum/autonumeric-rails#9]
I have two terminals, one is running "rails server", the other one "rails console". The second one, when starting the console, outputs this error message:

```
** ERROR: directory is already being watched! **
Directory: /my/path/.rvm/gems/ruby-2.3.1@project/gems/autonumeric-rails-1.9.46/spec/dummy/spec
is already being watched through: /my/path/.rvm/gems/ruby-2.3.1@project/gems/autonumeric-rails-1.9.46/spec
MORE INFO: https://github.com/guard/listen/wiki/Duplicate-directory-errors
```

Any ideas what would cause this?

**Comment by randoum** [comment]
autonumeric-rails is not using guard, no idea what could be the cause of this problem. Sorry

**Comment by groe** [comment]
Hm that's strange because my rails project doesn't use guard either. Anyway, thanks.

**Comment by groe** [comment]
@randoum According to the error message, the problem is that the `listen` gem (included in any new rails app), can not handle symlinks correctly which could cause performance problems and other unexpected problems. And it appears that the autoNumeric gem has a symlink at  `spec/dummy/spec` pointing to `spec`. So this could affect many rails apps, even if they don't use any specific gems other than the default listen gem.

What is the purpose of the symlink at `spec/dummy/spec`? Is it required?

**Comment by randoum** [comment]
Understood. Cannot fix it right now.

For the meantime you can delete the directory /my/path/.rvm/gems/ruby-2.3.1@project/gems/autonumeric-rails-1.9.46/spec
The spec directory is needed for testing the gem, you do not need it for your application development, testing, nor production.

**Comment by groe** [comment]
Ok, thank you @randoum

**Comment by randoum** [comment]
@groe I have removed the simlink from the spec directory structure. You should not have the bug with the listen gem anymore. Kindly update to 1.9.46.2 and let me know if the problem is solved.

**Comment by groe** [comment]
With 1.9.46.2 the warning message is gone, thank you @randoum!

**Comment by igbanam** [comment]
If you want to continue using `listen`, they have something up on [their wiki](https://github.com/guard/listen/wiki/Duplicate-directory-errors) addressing this. If you want to do away with listen for this bit, remove the line for `config.file_watchers` in your `config/environments/development.rb` file
